version: '3'
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always

  valkey:
    image: valkey/valkey
    container_name: valkey
    ports:
      - "6380:6379"
    restart: always
